services:
  server:
    container_name: server
    build: ./coap_server
    ports:
      - '5683:5683'
    network_mode: "host"

  mysql:
    hostname: mysql
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: manexmanex
      MYSQL_DATABASE: iotDB
    ports:
      - '3306:3306'  # Expose MySQL port
    networks:
      my_net:
        ipv4_address: 172.20.0.11
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    hostname: grafana
    container_name: grafana
    ports:
      - '3000:3000'
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - my_net

networks:
  my_net:
    name: my_net
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mysql-data:
  grafana-data:
